apiVersion: v1
kind: ConfigMap
metadata:
  name: n8n-config
  namespace: n8n
data:
  DB_TYPE: "postgresdb"
  DB_POSTGRESDB_HOST: "postgres"
  DB_POSTGRESDB_PORT: "5432"
  DB_POSTGRESDB_DATABASE: "n8n"
  DB_POSTGRESDB_USER: "n8n"
  DB_POSTGRESDB_SCHEMA: "public"

  EXECUTIONS_MODE: "queue"
  QUEUE_BULL_REDIS_HOST: "redis"
  QUEUE_BULL_REDIS_PORT: "6379"
  QUEUE_BULL_REDIS_DB: "0"

  N8N_HOST: "n8n.example.com"
  N8N_PROTOCOL: "https"
  N8N_PORT: "5678"
  WEBHOOK_URL: "http://n8n.example.com/"

  N8N_SECURE_COOKIE: "true"
  N8N_BLOCK_ENV_ACCESS_IN_NODE: "true"

  N8N_PAYLOAD_SIZE_MAX: "16777216"
  EXECUTIONS_DATA_SAVE_ON_ERROR: "all"
  EXECUTIONS_DATA_SAVE_ON_SUCCESS: "all"
  EXECUTIONS_DATA_PRUNE: "true"
  EXECUTIONS_DATA_MAX_AGE: "168"

  GENERIC_TIMEZONE: "Europe/Istanbul"
