{{- if and .Values.backup.enabled .Values.backup.storage.persistentVolume.enabled (not .Values.backup.storage.existingClaim) }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "n8n.fullname" . }}-backup-pvc
  labels:
    {{- include "n8n.labels" . | nindent 4 }}
spec:
  accessModes:
    {{- toYaml .Values.backup.storage.persistentVolume.accessModes | nindent 4 }}
  resources:
    requests:
      storage: {{ .Values.backup.storage.persistentVolume.size }}
  {{- if .Values.backup.storage.persistentVolume.storageClassName }}
  storageClassName: {{ .Values.backup.storage.persistentVolume.storageClassName }}
  {{- end }}
{{- end }}
