apiVersion: v1
kind: Service
metadata:
  name: n8n-service
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: n8n-main
  ports:
  - port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.targetPort }}
  type: {{ .Values.service.type }}
