{{- if .Values.gateway.enabled }}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: n8n-http
  namespace: {{ .Values.namespace }}
spec:
  hostnames:
    - {{ .Values.gateway.host }}
  parentRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: {{ .Values.gateway.name }}
      namespace: {{ .Values.gateway.namespace }}
  rules:
    - backendRefs:
        - name: n8n-service
          namespace: {{ .Values.namespace }}
          port: {{ include "service.port" . }}
      matches:
        - path:
            type: PathPrefix
            value: /
{{- end }}
