{{- if include "postgresql.enabled" . }}
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: postgres
  ports:
    - protocol: TCP
      port: {{ include "postgresql.port" . }}
      targetPort: {{ include "postgresql.port" . }}
{{- end }}
