{{- if include "redis.enabled" . }}
apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: {{ .Values.namespace }}
  labels:
    app: redis
spec:
  clusterIP: None
  selector:
    app: redis
  ports:
  - name: redis
    port: {{ include "redis.port" . }}
    targetPort: {{ include "redis.port" . }}
{{- end }}
