{{- if include "redis.enabled" . }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis
  namespace: {{ .Values.namespace }}
spec:
  serviceName: "redis"
  replicas: {{ include "redis.replicas" . }}
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        image: {{ include "redis.image.repository" . }}:{{ include "redis.image.tag" . }}
        imagePullPolicy: {{ include "redis.image.pullPolicy" . }}
        args:
        - redis-server
        - --appendonly
        - {{ .Values.redis.appendOnly | default "yes" | quote }}
        - --maxmemory
        - {{ .Values.redis.maxMemory | default "256mb" | quote }}
        - --maxmemory-policy
        - {{ .Values.redis.maxMemoryPolicy | default "allkeys-lru" | quote }}
        ports:
        - containerPort: {{ include "redis.port" . }}
        volumeMounts:
        - name: redis-data
          mountPath: /data
        {{- with .Values.redis.resources }}
        resources:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        livenessProbe:
          tcpSocket:
            port: {{ include "redis.port" . }}
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          exec:
            command:
            - redis-cli
            - ping
          initialDelaySeconds: 5
          periodSeconds: 5
  volumeClaimTemplates:
  - metadata:
      name: redis-data
    spec:
      storageClassName: {{ include "redis.storage.storageClassName" . }}
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: {{ include "redis.storage.size" . }}
{{- end }}
