{{- if .Values.gateway.enabled }}
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: {{ include "n8n.fullname" . }}-http
  labels:
    {{- include "n8n.labels" . | nindent 4 }}
spec:
  parentRefs:
  - name: {{ .Values.gateway.name }}
    namespace: {{ .Values.gateway.namespace | default .Release.Namespace }}
  hostnames:
  - "{{ .Values.gateway.host }}"
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /
    backendRefs:
    - name: {{ include "n8n.fullname" . }}-main
      port: 5678
{{- end }}
